import { CSSProperties } from 'react';

export const styles: { [key: string]: CSSProperties | any } = {
    calendarContainer: {
        '--primary': '#6366f1',
        '--event-bg': 'rgba(99, 102, 241, 0.15)',
        '--event-text': '#4338ca',
        '--bg-color': '#fff',
        '--text-main': '#000',
        '--event-cancelled-text': '#ef4444',
        '--event-cancelled-bg': '#ffe8e8',
        fontFamily: "'Inter', system-ui, sans-serif",
        background: 'var(--bg-color)',
        backdropFilter: 'blur(16px)',
        WebkitBackdropFilter: 'blur(16px)',
        border: '1px solid var(--glass-border)',
        borderRadius: '24px',
        padding: '24px',
        boxShadow:
            '0 20px 40px rgba(0, 0, 0, 0.1), inset 0 1px 0 rgba(255, 255, 255, 0.2)',
        color: 'var(--text-main)',
        maxWidth: '1200px',
        margin: '0 auto',
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
        overflow: 'hidden',
        transition: 'all 0.3s ease',
    },

    gridContainer: {
        flexGrow: 1,
        position: 'relative',
        minHeight: '600px',
    },

    popupOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: 'rgba(0, 0, 0, 0.4)',
        backdropFilter: 'blur(4px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 100,
    },
    popupContainer: {
        background: 'var(--bg-color)',
        border: '1px solid var(--border-color)',
        borderRadius: '16px',
        padding: '24px',
        width: '400px',
        maxWidth: '90%',
        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    popupHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottom: '1px solid var(--border-color)',
        paddingBottom: '12px',
    },
    popupTitle: {
        fontSize: '1.25rem',
        fontWeight: 600,
        margin: 0,
    },
    popupCloseBtn: {
        background: 'transparent',
        border: 'none',
        cursor: 'pointer',
        color: 'var(--text-muted)',
        padding: '4px',
    },
    popupBody: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    popupDetailRow: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    popupLabel: {
        fontSize: '0.85rem',
        color: 'var(--text-muted)',
        fontWeight: 600,
        textTransform: 'uppercase',
    },
    popupValue: {
        fontSize: '1rem',
        color: 'var(--text-main)',
    },
    popupActions: {
        display: 'flex',
        gap: '12px',
        marginTop: '8px',
    },
    btnDanger: {
        background: 'rgba(239, 68, 68, 0.15)',
        color: '#ef4444',
        border: '1px solid rgba(239, 68, 68, 0.3)',
        flex: 1,
    },
    btnSecondary: {
        background: 'var(--surface)',
        color: 'var(--text-main)',
        border: '1px solid var(--border-color)',
        flex: 1,
    },
    inputField: {
        background: 'var(--surface)',
        border: '1px solid var(--border-color)',
        color: 'var(--text-main)',
        padding: '8px 12px',
        borderRadius: '8px',
        fontSize: '1rem',
        width: '100%',
        boxSizing: 'border-box',
    },
};
